[theme]
primaryColor = "#4a9e3f"
backgroundColor = "#0a140c"
secondaryBackgroundColor = "#0e1c11"
textColor = "#e8edd0"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
